apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: load-balancer-demo
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  # loadBalancerIP: 10.70.154.15
